In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
import re

In [2]:
df = pd.read_csv('../data/Rates_and_Trends_in_Heart_Disease.csv')

C:\Users\adisu\AppData\Local\Temp\ipykernel_38580\4217082028.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/Rates_and_Trends_in_Heart_Disease.csv')

In [3]:
df

,Year,LocationAbbr,LocationDesc,GeographicLevel,DataSource,Class,Topic,Data_Value,Data_Value_Unit,Data_Value_Type,...,Data_Value_Footnote,Confidence_limit_Low,Confidence_limit_High,StratificationCategory1,Stratification1,StratificationCategory2,Stratification2,StratificationCategory3,Stratification3,LocationID
0,1999,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,NaN,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,Value suppressed,NaN,NaN,Age group,Ages 35-64 years,Race,American Indian/Alaska Native,Sex,Overall,1001
1,2013,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,NaN,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,Value suppressed,NaN,NaN,Age group,Ages 35-64 years,Race,American Indian/Alaska Native,Sex,Overall,1001
2,2014,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,NaN,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,Value suppressed,NaN,NaN,Age group,Ages 35-64 years,Race,American Indian/Alaska Native,Sex,Overall,1001
3,2005,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,NaN,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,Value suppressed,NaN,NaN,Age group,Ages 35-64 years,Race,American Indian/Alaska Native,Sex,Overall,1001
4,2012,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,NaN,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,Value suppressed,NaN,NaN,Age group,Ages 35-64 years,Race,American Indian/Alaska Native,Sex,Overall,1001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5770235,1999 - 2010,WY,Weston,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),-33.4,%,Total percent change,...,NaN,-46.3,-19.5,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
5770236,2010 - 2019,WY,Weston,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),-6.7,%,Total percent change,...,NaN,-20.4,5.7,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
5770237,1999 - 2010,WY,Weston,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),-31.5,%,Total percent change,...,NaN,-41.0,-20.4,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
5770238,1999 - 2010,WY,Weston,County,NVSS,Cardiovascular Diseases,Heart failure,-20.0,%,Total percent change,...,NaN,-41.7,-2.9,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
5770239,2010 - 2019,WY,Weston,County,NVSS,Cardiovascular Diseases,Heart failure,-1.9,%,Total percent change,...,NaN,-23.0,20.2,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045

In [4]:
df.drop('Data_Value_Footnote_Symbol', axis =1, inplace =True)

In [14]:
df.loc[df['Year']] == 2012

KeyError: "['2008', '2010', '2014', '2016', '2007', '2000', '2002', '2003', '2005', '1999', '2013', '2004', '2001', '2017', '2006', '2009', '2012', '2015', '2018', '2019', '2011', '1999 - 2010', '2010 - 2019'] not in index"

In [20]:
filtered_df = df.query("Year >= '2001' & Year <= '2010'")

TypeError: '>=' not supported between instances of 'int' and 'str'

In [17]:
result = df.query("Year == '2010'")
result

,Year,LocationAbbr,LocationDesc,GeographicLevel,DataSource,Class,Topic,Data_Value,Data_Value_Unit,Data_Value_Type,Data_Value_Footnote,Confidence_limit_Low,Confidence_limit_High,StratificationCategory1,Stratification1,StratificationCategory2,Stratification2,StratificationCategory3,Stratification3,LocationID
5210113,2010,WI,Taylor,County,NVSS,Cardiovascular Diseases,All heart disease,NaN,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",Value suppressed,NaN,NaN,Age group,Ages 35-64 years,Race,Asian/Pacific Islander,Sex,Overall,55119
5210136,2010,WI,Taylor,County,NVSS,Cardiovascular Diseases,All stroke,NaN,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",Value suppressed,NaN,NaN,Age group,Ages 35-64 years,Race,Asian/Pacific Islander,Sex,Overall,55119
5210162,2010,WI,Taylor,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),NaN,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",Value suppressed,NaN,NaN,Age group,Ages 35-64 years,Race,Asian/Pacific Islander,Sex,Overall,55119
5210178,2010,WI,Taylor,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),NaN,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",Value suppressed,NaN,NaN,Age group,Ages 35-64 years,Race,Asian/Pacific Islander,Sex,Overall,55119
5210199,2010,WI,Taylor,County,NVSS,Cardiovascular Diseases,Heart failure,NaN,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",Value suppressed,NaN,NaN,Age group,Ages 35-64 years,Race,Asian/Pacific Islander,Sex,Overall,55119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5268395,2010,WY,Weston,County,NVSS,Cardiovascular Diseases,All heart disease,1062.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",NaN,971.0,1199.1,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
5268418,2010,WY,Weston,County,NVSS,Cardiovascular Diseases,All stroke,253.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",NaN,217.8,290.1,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
5268441,2010,WY,Weston,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),601.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",NaN,517.0,698.1,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
5268458,2010,WY,Weston,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),1388.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",NaN,1256.3,1605.3,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
5268480,2010,WY,Weston,County,NVSS,Cardiovascular Diseases,Heart failure,505.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",NaN,417.6,584.6,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045

In [10]:
df2 = df.loc[df['LocationAbbr'] == 'RI']

In [11]:
df2.loc[df2['LocationDesc'] == 'Bristol']

,Year,LocationAbbr,LocationDesc,GeographicLevel,DataSource,Class,Topic,Data_Value,Data_Value_Unit,Data_Value_Type,Data_Value_Footnote,Confidence_limit_Low,Confidence_limit_High,StratificationCategory1,Stratification1,StratificationCategory2,Stratification2,StratificationCategory3,Stratification3,LocationID
3871678,2009,RI,Bristol,County,NVSS,Cardiovascular Diseases,All stroke,6.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",NaN,5.4,8.7,Age group,Ages 35-64 years,Race,Overall,Sex,Women,44001
3871735,2002,RI,Bristol,County,NVSS,Cardiovascular Diseases,All stroke,7.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",NaN,6.2,10.0,Age group,Ages 35-64 years,Race,Overall,Sex,Women,44001
3872102,2003,RI,Bristol,County,NVSS,Cardiovascular Diseases,All stroke,7.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",NaN,6.3,9.4,Age group,Ages 35-64 years,Race,Overall,Sex,Women,44001
3872268,2006,RI,Bristol,County,NVSS,Cardiovascular Diseases,All stroke,6.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",NaN,5.4,8.4,Age group,Ages 35-64 years,Race,Overall,Sex,Women,44001
3872404,1999,RI,Bristol,County,NVSS,Cardiovascular Diseases,All heart disease,NaN,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",Value suppressed,NaN,NaN,Age group,Ages 35-64 years,Race,American Indian/Alaska Native,Sex,Overall,44001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5637452,1999 - 2010,RI,Bristol,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),-40.0,%,Total percent change,NaN,-48.2,-29.4,Age group,Ages 65 years and older,Race,White,Sex,Overall,44001
5637453,2010 - 2019,RI,Bristol,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),-1.5,%,Total percent change,NaN,-11.9,10.1,Age group,Ages 65 years and older,Race,White,Sex,Overall,44001
5637454,1999 - 2010,RI,Bristol,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),-34.5,%,Total percent change,NaN,-42.8,-26.9,Age group,Ages 65 years and older,Race,White,Sex,Overall,44001
5637455,1999 - 2010,RI,Bristol,County,NVSS,Cardiovascular Diseases,Heart failure,1.8,%,Total percent change,NaN,-17.6,24.8,Age group,Ages 65 years and older,Race,White,Sex,Overall,44001
5637456,2010 - 2019,RI,Bristol,County,NVSS,Cardiovascular Diseases,Heart failure,18.3,%,Total percent change,NaN,-0.9,46.8,Age group,Ages 65 years and older,Race,White,Sex,Overall,44001

In [5]:
df['Year'].unique

<bound method Series.unique of 0                 1999
1                 2013
2                 2014
3                 2005
4                 2012
              ...
5770235    1999 - 2010
5770236    2010 - 2019
5770237    1999 - 2010
5770238    1999 - 2010
5770239    2010 - 2019
Name: Year, Length: 5770240, dtype: object>

In [8]:
df['Year'].str.extract(r'(\d{4})')

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
...       ...
5770235  1999
5770236  2010
5770237  1999
5770238  1999
5770239  2010

[5770240 rows x 1 columns]

In [6]:
### df['Year'] = pd.to_datetime(df['Year'], format='%y')